-----------------------------------------------------------
-- |
-- module:                      MXNet.Core.Base.Internal.TH.Symbol
-- copyright:                   (c) 2016 Tao He
-- license:                     MIT
-- maintainer:                  sighingnow@gmail.com
--
-- Functions about Symbol that generated by template haskell.
--
{-# OPTIONS_GHC -Wno-missing-signatures #-}
{-# LANGUAGE TemplateHaskell #-}

module MXNet.Core.Base.Internal.TH.Symbol where

import MXNet.Core.Base.Internal.TH (registerSymbolOps)

$(registerSymbolOps)
