-----------------------------------------------------------
-- |
-- module:                      MXNet.Core.Base.Native.NDArray
-- copyright:                   (c) 2016 Tao He
-- license:                     MIT
-- maintainer:                  sighingnow@gmail.com
--
-- Functions about NDArray that generated by template haskell.
--
{-# LANGUAGE TemplateHaskell #-}

module MXNet.Core.Base.Native.NDArray where

import MXNet.Core.Base.Internal.TH ( registerNDArrayOps )

$(registerNDArrayOps)
