-----------------------------------------------------------
-- |
-- module:                      MXNet.Core.Base.Native.Symbol
-- copyright:                   (c) 2016 Tao He
-- license:                     MIT
-- maintainer:                  sighingnow@gmail.com
--
-- Functions about Symbol that generated by template haskell.
--
{-# LANGUAGE TemplateHaskell #-}

module MXNet.Core.Base.Native.Symbol where

import MXNet.Core.Base.Internal.TH ( registerSymbolOps )

$(registerSymbolOps)
